#!/usr/bin/env bash
#fizzbuzz First complex :) fizzbuzz multiple of 3 and 5 then fizz for 3 buzz for 5
for i in {1..100}; do
    if (( i % 15 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
