#!/usr/bin/env bash
# 4,9,17 the good the bad and the ugly
i=1
while [ $i -le 20 ]; do
    case $i in
        4) echo "$i"; echo "bad luck from China" ;;
        9) echo "$i"; echo "bad luck from Japan" ;;
        17) echo "$i"; echo "bad luck from Italy" ;;
        *) echo "$i" ;;
    esac
    ((i++))
done
