#!/usr/bin/env bash
#using trap
termer() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}
inter() {
	echo ""
	echo "Y U no love me?!"
}
quiter() {
	rm -f /var/run/myscript.pid
        exit 0
}

trap termer SIGTERM
trap inter SIGINT
trap quiter SIGQUIT

echo $BASHPID > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 2
done
