#!/usr/bin/env bash
#using trap
PIDFILE="/var/run/myscript.pid"
sudo chown student_jail:student_jail /var/run/myscriptsudo chown student_jail:student_jail /var/run/myscript.pid
echo $BASHPID > $PIDFILE

termer() {
    echo "I hate the kill command"
    rm -f $PIDFILE
    exit 0
}
inter() {
	echo "Y U no love me?!"
}
quiter() {
	rm -f $PIDFILE
        exit 0
}

trap termer SIGTERM
trap inter SIGINT
trap quiter SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
